name: Auto-format Markdown

on:
  push:
    branches: [ main ]
    paths: [ '**/*.md' ]
  pull_request:
    branches: [ main ]
    paths: [ '**/*.md' ]

# Add permissions block
permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install markdownlint
      run: npm install -g markdownlint-cli

    - name: Fix YAML frontmatter issues
      run: |
        echo "🔧 Fixing YAML frontmatter issues..."
        
        # Function to fix YAML issues
        fix_yaml() {
          local file="$1"
          echo "  Checking: $file"
          
          # Fix unquoted authors arrays
          sed -i 's/authors: \[\(@[^]]*\)\]/authors: ["\1"]/g' "$file"
          
          # Fix multiple authors in array
          sed -i 's/authors: \[\(@[^,]*\), \(@[^]]*\)\]/authors: ["\1", "\2"]/g' "$file"
          
          # Fix unquoted titles with special characters
          sed -i 's/^title: \([^"'\'']*[:\[\]|][^"'\'']*\)$/title: "\1"/g' "$file"
          
          # Fix unquoted timeline with special characters  
          sed -i 's/^timeline: \([^"'\'']*[:\[\]|][^"'\'']*\)$/timeline: "\1"/g' "$file"
          
          # Ensure tags field exists
          if ! grep -q "^tags:" "$file" && grep -q "^---$" "$file"; then
            sed -i '/^priority:/a tags: []' "$file"
          fi
        }
        
        # Fix all research files
        find . -name "*.md" -path "./initiatives/*" -o -path "./templates/*" | while read file; do
          if grep -q "^---$" "$file"; then
            fix_yaml "$file"
          fi
        done

    - name: Format markdown files
      run: |
        echo "🔧 Formatting markdown files..."
        find . -name "*.md" -exec markdownlint --fix {} + || true

    - name: Check for changes
      id: verify-changed-files
      run: |
        changes=$(git status --porcelain)
        if [ -n "$changes" ]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Get modified files
      if: steps.verify-changed-files.outputs.changed == 'true'
      id: changed-files
      run: |
        # Get list of modified markdown files
        {
          echo 'files<<EOF'
          git ls-files -m "*.md"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: swinton/commit@v2.x
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ steps.changed-files.outputs.files }}
        commit-message: |
          🤖 Auto-format markdown files

          - Fixed YAML frontmatter syntax
          - Applied consistent markdown formatting
          - Ensured proper code style
          
          [skip ci]
        ref: refs/heads/${{ github.head_ref || github.ref_name }} 